//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PartCont.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Description
    {
        public int desc_id { get; set; }
        public Nullable<int> cont_id { get; set; }
        public string descript { get; set; }
    
        public virtual Contracts Contracts { get; set; }
    }
}
