//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PartCont.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CPartnersDBEntities : DbContext
    {
        public static CPartnersDBEntities _context;

        public CPartnersDBEntities()
            : base("name=PartnersDBEntities1")
        {
        }

        public static CPartnersDBEntities GetContext()
        {
            if (_context == null)
                _context = new CPartnersDBEntities();
            return _context;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Contracts> Contracts { get; set; }
        public virtual DbSet<Description> Description { get; set; }
        public virtual DbSet<Partners> Partners { get; set; }
    }
}
